### PR TITLE
Feature/#commander

### PR DESCRIPTION
**Pull request by oreyes1991**
## First iteration of docstrap.
in this first iteration the project is mainly node js, is design as a commander.

### how to run it in your dev environment?
install dependencies
```bash
npm install
```
Run the project itself
```bash
node index.js [-d ]
```
the optional parameter -d stands for dir and will spawn your documentation web-view in that dir if not specified will be created under the docs/ folder.
- After creation, every .md file will be parsed into their respective HTML index file.
- If the dir folder exists will override the web-view but not the .md so any change done in your documentation will be deployed successfully on your views.
- notice that the parsing the .md files is done on the server-side, so any update in your documentation must be built, in this way we can easily set it up with Travis. 
- notices there is no code generation in the client-side so every view will be plain static HTML.

### example
if I have a .md with this info
```
# Documentation header
```
the respective HTML index will be generated with
```html
<h1 id="documentaion-header">Documentation header</h1>
```

### CODE REVIEW

**Comment by jegj** [comment]
Looking forward to this PR

**Comment by oreyes1991** [comment]
> Looking forward

The Jekyll template is almost done, after that I can replace the HTML template for the Jekyll one, the commander should do the same, so just small adaptation has to be done.

**Comment by jegj** [comment]
Let me know so I can test the deploy pipeline

**Comment by oreyes1991** [comment]
## Added Jekyll template
The new template is a theme-based Jekyll project, the theme maintains the preview styles and views, and bring new stuff with it:
- _config.yml is the main configuration for the site, is the top-level when parsing.
- Gemfile is the package manager, here you can see dependencies
## Building project
```bash
node index.js
```
This will generate the docs/ folder if it doesn't exist, if exist will overwrite the template but not the configuration files or Markdown files (.md).
```bash
cd ./docs
bundle exec jekyll build
```
this will build the template into a _site/ folder.
## Requirements 
you need
-  Ruby gem
- Jekyll
to install both you can find it [here](https://jekyllrb.com/docs/installation/ubuntu/)

**Comment by jegj** [comment]
is this PR ready for revision?

**Comment by oreyes1991** [comment]
> is this PR ready for revision?

I'm doing a quick QA and polishing syntax, I will put it ready for revision later today.

**Review by pablolimo — APPROVED** [review]

**Review by jegj — APPROVED** [review]

**Review by ReinsBrain — APPROVED** [review]

**Pull request merged**
